[build]
  command = "pip install ."
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.12"

# Explicitly define the 'main' function
[functions]
  # Directory containing this specific function's handler file (main.py)
  directory = "quicksync/src/"

[[redirects]]
  from = "/contacts/*"
  to = "/.netlify/functions/main"
  status = 200