[build]
  command = "pip install -e ."
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/contacts/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200